### ISSUE TITLE
possible bug with a string such as 0 0 * 6 1

### ISSUE THREAD

**Issue by amortiz** [harrisiirak/cron-parser#223] opened 2021-04-13 20:51 UTC
shouldn't a cron string of 0 0 * 6 1 execute at times such as: 
2021-06-07 00:00:00
2021-06-14 00:00:00
2021-06-21 00:00:00
2021-06-28 00:00:00
2022-06-06 00:00:00

However when i use cron-parser, i see

June 1, 2021 12:00:00 AM 
June 2, 2021 12:00:00 AM 
June 3, 2021 12:00:00 AM 
June 4, 2021 12:00:00 AM 
June 5, 2021 12:00:00 AM 

It's as if the day-of-week and month parameters are not playing nice together.

**Comment by harrisiirak** [comment] 2021-04-13 21:37
@amortiz thanks for reporting this. This is somehow related to #173 (and other similar reports from the past).

> If month, day of month, and day of week are all asterisks, every day shall be matched. If either the month or day of month is specified as an element or list, but the day of week is an asterisk, the month and day of month fields shall specify the days that match. If both month and day of month are specified as an asterisk, but day of week is an element or list, then only the specified days of the week match. **Finally, if either the month or day of month is specified as an element or list, and the day of week is also specified as an element or list, then any day matching either the month and day of month, or the day of week, shall be matched.**

So basically:

> Finally, if either the month or day of month is specified as an element or list, and the day of week is also specified as an element or list, then any day matching either the month and day of month, or the day of week, shall be matched. 

Dissecting this:

> Finally, if either the month or day of month is specified as an element or list

month is an element (day of month is wildcard)

> and the day of week is also specified as an element or list

day of week is an element

> then any day matching either the month and day of month, or the day of week, shall be matched. 

- it will match if day of week is 1
- it will match if month is 6 
- it will match if any day of month (1-31)

As day of month is wildcard, it will include all the days. It doesn't say that day of month should be ignored when it's defined as wildcard (asterisk).

You expected behaviour (match by day of week) would only happen under this condition:

> If both month and day of month are specified as an asterisk, but day of week is an element or list, then only the specified days of the week match

Based on the spec I'm using, this should be expected behaviour. But maybe I'm missing something?

**Comment by amortiz** [comment] 2021-04-13 22:36
@harrisiirak thanks for the response. So i was looking at https://crontab.guru/#0_0_*_6_1 , and it doesn't match up. I thought your response made sense for when day of week and day of month are both specified.

**Comment by harrisiirak** [comment] 2021-04-14 07:24
> So i was looking at https://crontab.guru/#0_0_*_6_1 , and it doesn't match up.

Yep, I've also used Crontab.guru in the past and it's incredibly useful tool. In this scenario, I don't think that they are actually implementing this behaviour correctly. At least, it seems that they are using some kind of weird shortcuts to solve this complexity of handling day of month/day of week/month simultaneous usage in the pattern.

If to humanize this expression by the specification, then it should say: `At 00:00 on every day-of-month  or on Monday in June.` (then any day matching either the month and day of month, or the day of week, shall be matched)

However, in Crontab.guru it translates as `At 00:00 on Monday in June.`

Also some weird behaviour from Crontab.guru:

- https://crontab.guru/#0_0_1-1_6_1 (invalid range btw)
- https://crontab.guru/#0_0_1-31_6_1 (yields the same results as `cron-parser` atm)

But yeah, I see that CronHub is also behaving similarly to Crontab.guru: https://crontab.cronhub.io/
I would really like to ear more opinions about this behaviour, before really changing anything about this behaviour. It's definitely interesting discussion (so I'm not closing this issue).

**Comment by amortiz** [comment] 2021-04-14 13:06
@harrisiirak actually, after playing around with some more strings, I think there is a bug here.
when i do `0 0 * 6 1` as described above, it does every day in June as we discussed
however when i do `0 0 * 7 1` it does only every monday in july, and it matches what i think should be the correct behavior and crontab.guru

further, i realized that this "discrepancy" happens on all months that don't have 31 days. 
`0 0 * 1 1`  <--correct 
`0 0 * 2 1`  <--incorrect  
`0 0 * 3 1`  <--correct 
`0 0 * 4 1`  <--incorrect 
`0 0 * 5 1`  <--correct 
`0 0 * 6 1`  <--incorrect 
`0 0 * 7 1`  <--correct 
`0 0 * 8 1`  <--correct 
`0 0 * 9 1`  <--incorrect 
`0 0 * 10 1`  <--correct 
`0 0 * 11 1`  <--incorrect 
`0 0 * 12 1`  <--correct

**Comment by harrisiirak** [comment] 2021-04-14 13:24
@amortiz a good catch. Indeed, looking this from that perspective, it looks like a bug to me. It seems that `isDayOfMonthWildcardMatch` returns false for non 31 day months when day of month value is asterisk. I'll investigate this.

**Comment by harrisiirak** [comment] 2021-04-14 15:26
@amortiz I actually found the bug and fix for it. 63b6d3edf5b8037aa31a1721e583d03a3af44a1e
However, I need to test it a bit more (tests are currently passing) and harden/improve existing tests.

**Closed** 2021-04-20 16:28 UTC
Labels: bug
