### ISSUE TITLE
is the parse result right ? '0 5/10 * * * *'

### ISSUE THREAD

**Issue by kkdev163** [harrisiirak/cron-parser#164] opened 2019-07-16 12:37 UTC
I expect to get time series like this:
10:05  10:15 10:25 10:35...

but the parse result is like:
10:05  11:05 12:05 13:05.

is the current parse result right?

to get my expect parse result,i should write the expression like this: '0 5,15,25,35,45,55 * * * *'.

**Comment by 15190480986** [comment] 2019-07-17 01:42
I had the same problem.
If the expression'3/40 1/3 * * * ?' or '*/20 */2 * * * ?' , the parser cannot return the result correctly.

**Comment by kaos** [comment] 2019-07-17 07:40
what you want is most likely `0 5-59/10 * * *`
The step modifier (`/10` in this case) works within a range, not from a single value.

**Comment by harrisiirak** [comment] 2019-07-21 16:19
Duplicate of #156

**Closed by harrisiirak** 2019-07-21 16:19 UTC
